name: Deploy Hugo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload site artifact
        uses: actions/upload-artifact@v7
        with:
          name: hudocs-build
          path: ./public
          retention-days: 1

  deploy-github-pages:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: hudocs-build
          path: ./public

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  deploy-cloudflare-pages:
    needs: build
    environment:
      name: cloudflare-pages
      url: ${{ steps.cf_deployment.outputs.deployment-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: hudocs-build
          path: ./public

      - name: Deploy to Cloudflare Pages
        id: cf_deployment
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./public --project-name=channel101